#!/usr/bin/python3
# RSA Factoring Challenge

import sys

def factorize(n):
    factors = []
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            factors.append((i, n // i))
    return factors

def main(file_path):
    with open(file_path, 'r') as file:
        numbers = file.readlines()

    for number in numbers:
        n = int(number.strip())
        factorizations = factorize(n)
        for factorization in factorizations:
            p, q = factorization
            print(f"{n}={p}*{q}")

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
    else:
        file_path = sys.argv[1]
        main(file_path)
